# .github/workflows/main.yml
name: CI/CD Test Workflow

on:
  push:
    branches:
      - lab3

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a simple script
        run: echo "Hello, GitHub Actions!"
