# .github/workflows/main.yml
name: CI/CD Test Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

  #push:
  #  branches:
  #    - lab3

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show system info
        run: |
          echo OS Info:
          systeminfo
          echo CPU Info:
          wmic cpu get name,NumberOfCores,NumberOfLogicalProcessors
          echo Memory Info:
          wmic memorychip get capacity,manufacturer,partnumber,speed

      - name: Run a simple script
        run: echo "Hello, GitHub Actions!"
